 # Python review 

Review about some core concepts in Python exemplified by objects in the NumPy library. 

Goals: 
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple ones. 

**NumPy:**  
- core library for numerical computing in Python. 
- many of the libraries use NumPy's arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy using the **standard abbreviation** `np`:

In [1]:
import numpy as np

## Variables

**variable:** a name that we assign to a particular object in Python.

Example:

In [2]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

To view a variable's value from within our Jupyter notebook:

In [3]:
# Show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Print the value 
print(a)

[[1 1 2]
 [3 5 8]]


*Comments should start with a capital letter.*

## R and Python: assigning values

Remember that in Python we use the equal sign `=` to assign values to variables in the same way the left-arrow `<-` is used in R:
``` R
# R: assign value 10 to variable a
a <- 10
```

``` R
# Python: assign value 10 to variable a
a = 10
```
## Convention: Use `snake_case` for naming variables

There are many ways of constructing multi-word variable names. 



## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific.

Example:

- Object: data frame

- Properties: number of rows, names of columns, and date created

- Actions: selecting a specific row or adding a new column. 

A variable is the name we give a specific object, and the same object can be referenced by different variables. 


In practice, we can often use the word variable and object interchangeably.


## Types

Every object in Python has a **type**, the type tells us what kind of object it is. We can also call the type of an object, the **class** of an object, so class and type both mean what kind of object we have. 


In [12]:
print(a)
# See the type/class of a variable/object by using the `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy package.

In [16]:
print(a[0,0])
# Check the type of an entry in the array by indexing
type(a[0,0])

1


numpy.int64

Notice the type of the value 1 in the array is `numpy.int64` and not just the standard Python integer type `int`. 

The NumPy type `numpy.int64` is telling us 1 is an integer stored as a 64-bit number. 

## R and Python: indexing



A way to understand this 0-indexing is that, in Python, the index indicates the *displacement* from the start of the collection. So '0 index in an array' means 'zero displacement from the start of the array', in other words, the first element of the array. 

## Check-in
How would you access the value 5 in the array `a`?


In [9]:
print(a[1,1])
type(a[1,1])

5


numpy.int64



## Functions

`print` was our first example of a Python **function**. 


**Functions:** take in a set of **arguments**, separated by commas, and then the function uses those arguments to create an **output**.

In the course: we will use argument and parameter interchangeably.

We can ask for information about what a function does by executing `?` followed by the function name:

In [10]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

What we obtain is a **docstring**, a special type of comment that is used to document how a function (or class, or module) works. 

You can see there are different types of arguments inside the function's parenthesis. Roughly speaking, a function has two types of arguments:

- **Non-optional arguments:** arguments *you* need to specify for the function to do something.
- **Optional arguments:** arguments that are pre-filled by the function with a default value, but you can override them. Optional arguments appear insude the parenthesis () in the form `optional_arg = default_value`.

Example: `end` is aparameter in `print()` with the default value a new line. We can pass the value `:)` to this parameter so that it finishes the line with `:)` instead:


In [11]:
print('changing the default end argument of the print function', end=' ^_^')

changing the default end argument of the print function ^_^

*Notice that before we had always used print without specifying any value for the `end` parameter.*


## Attributes & methods

An object in Python has attributes and methods. 

- **attribute:** a property of the object, some piece of information about it
- **method:** a procedure associated with an object, it is an action where the main ingredient is the object.

For example, these could be some attributes and methods for class `fish`:

VARIABLE: fish

METHODS:
- swim -> fish.swim()
- attack
- school
- blow bubbles

ATTRIBUTES:
- color -> fish.color
- weight
- number of fins

More formally, **a method is a function** that acts on the object it is part of.

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name:

`variable.variable_attribute`

## Check-in
Suppose we have a class `fish`, make a diagram similar to the `cat` class diagram showing 3 attributes for the class and 3 methods.


NumPy arrays have many methods and attributes. Let's see some concrete examples.

Examples of attributes:

In [13]:
# A 3x3 array
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`T` is an example of attribute, it returns the transpose of `var`:

In [14]:
print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


`shape`, another attribute, tells us the shape of the array:

In [15]:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


`ndim` is an attribute holding the number of array dimensions

In [17]:
print(var.ndim)
print(type(var.ndim))

2
<class 'int'>


Notice these attributes can have many different data types. 

Examples of methods:

The `tolist` method returns the array as a nested list of scalars:

In [18]:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

The `min` method returns the minimum value in the array along a specified axis:

In [19]:
var.min(axis=0)

array([1, 2, 3])

## Check-in

We can also call the `min` method without any parameters:

In [20]:
var.min()

np.int64(1)

What kind of parameter is `axis` in our previous call of the `min` method?


The `axis` parameter is an optional argument in min().


Remember, methods are functions associated to an object. We can confirm this!

In [21]:
type(var.tolist)

builtin_function_or_method

In [22]:
type(var.min)

builtin_function_or_method

## Exercise
1. Read the `print` function help. What is the type of the argument `sep`? Is this a default or non-default argument? Why? - `sep` is an optional parameter in `print()` because it has a default value.

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the default arguments in `print`.

In [23]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [24]:
num1 = 77
num2 = "99"

In [25]:
print(num1,num2,num1,sep="%")

77%99%77
